services:
  api:
    container_name: fastapi-dev
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app:rw
    environment:
      - PYTHONPATH=/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  db:
    image: mongo:6.0
    container_name: mongo-dev
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=mydatabase
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
